### PR TITLE
code/dte: add XML schemas of "factura electrónica"

### PR DESCRIPTION
**Pull request by yaselc**
Official XML schemas of DTE (Documento Tributario Electrónico)

Includes a README file by @glarrain

All the files have been preserved as they were; schemas are in their original text encoding (ISO-8859-1) and have not been modified in the slightest way.

Sources (2021-03-12):
http://www.sii.cl/factura_electronica/schema_dte.zip

Ref #11

### CODE REVIEW

**Comment by glarrain** [comment]
Idea:
- `src/code/factura_electronica/2011-05-30-schema_dte-vX.zip`
- `src/code/factura_electronica/2011-05-30-schema_dte-vX/schema_dte/*.xsd`

What do you think @yaselc @jtrh ?

**Comment by yaselc** [comment]
> * `src/code/factura_electronica/2011-05-30-schema_dte-vX.zip`
> * `src/code/factura_electronica/2011-05-30-schema_dte-vX/schema_dte/*.xsd`

@glarrain I'm not totally sure of the source of the information `2011-05-30` and` vX`, both are taken from SII?

Should we use a directory for each domain (DTE, RCV, RTC) or a common directory?

**Comment by glarrain** [comment]
> @glarrain I'm not totally sure of the source of the information `2011-05-30` and` vX`, both are taken from SII?

- `2011-05-30` taken from the last updated timestamp of the files in the ZIP file
- `vX` I added it just to indicate that the file does not have a version number/ID. Perhaps it is not useful and just adds noise.

> Should we use a directory for each domain (DTE, RCV, RTC) or a common directory?

You are right. I thought the ZIP contained the schemas of several domains but now I see it does not. Then, what do you think about this? `src/code/dte/2011-05-30-schema_dte/schema_dte/*.xsd`

**Comment by yaselc** [comment]
> * `2011-05-30` taken from the last updated timestamp of the files in the ZIP file

We intend to apply two updates to the XML schema but from different sources. What would happen to this prefix in that case, does it keep the date of the original file or is it updated with the date of the alternative source?

**Comment by jtrh** [comment]
> what do you think about this? `src/code/dte/2011-05-30-schema_dte/schema_dte/*.xsd`

:+1:

**Comment by jtrh** [comment]
> > * `2011-05-30` taken from the last updated timestamp of the files in the ZIP file
> 
> We intend to apply two updates to the XML schema but from different sources. What would happen to this prefix in that case, does it keep the date of the original file or is it updated with the date of the alternative source?

I'm not sure whether I'm understanding you correctly, @yaselc. Did you mean something like *"add new revision of `EnvioDTE_v10.xsd` obtained from `something_else_schemas.zip`"*?

**Comment by glarrain** [comment]
@yaselc ?

**Comment by glarrain** [comment]
@yaselc please finish PR https://github.com/cl-sii-extraoficial/archivos-oficiales/pull/12 so then you can finish this one

**Comment by yaselc** [comment]
> > > * `2011-05-30` taken from the last updated timestamp of the files in the ZIP file
> > 
> > 
> > We intend to apply two updates to the XML schema but from different sources. What would happen to this prefix in that case, does it keep the date of the original file or is it updated with the date of the alternative source?
> 
> I'm not sure whether I'm understanding you correctly, @yaselc. Did you mean something like _"add new revision of `EnvioDTE_v10.xsd` obtained from `something_else_schemas.zip`"_?

@jtrh sorry for the mistake, but your right, it would actually be a single update for the `DTE_v10.xsd` and `SiiTypes_v10.xsd` XSD files, taken from `schema_cesion_201912.zip`.

**Comment by yaselc** [comment]
> @yaselc please finish PR #12 so then you can finish this one

@glarrain I think your comment was aimed at another PR. Also, I applied the changes you suggested earlier in this PR, have you been able to look at it?

**Pull request closed without merging**
